### ISSUE TITLE
MySQL to SQLite

### ISSUE THREAD

**Issue by xxFLORII** [StimoMC/Suggestions#19]
This is necessary to get a better performance. All data will be transferred from the mysql database to the new sqlite database.
Once everything is ready, a downtime of up to one day is expected so that everything runs properly.

**Comment by Erkam246** [comment]
Are u serious?

**Comment by xxFLORII** [comment]
it‘s working better then excepted

**Comment by Erkam246** [comment]
How did you came to this conclusion that SQLite would be a better option in this case?

**Comment by xxFLORII** [comment]
It was suggested to me by some people from the PE & Java scene who are active in the field of development.

**Comment by xxFLORII** [comment]
done
