### ISSUE TITLE
/ban Überarbeiterung

### ISSUE THREAD

**Issue by Miniryuuu** [StimoMC/Suggestions#4]
/banlist 
zeigt Ban oder Mute Gründe sprich,man gibt ein banlist oder ähnliches und dann stehen da alle Gründe wie chatspamming oder Hacking und dann kriegt jeder Grund eine Zahl und dann sieht dass so aus ;
/ban (Name) (Reason: 1,2,3,4,5....)
Bei Unklarheit schreibt Discord

**Comment by xxAROX** [comment]
done!
