### ISSUE TITLE
speedbw

### ISSUE THREAD

**Issue by Miniryuuu** [StimoMC/Suggestions#5]
Anstatt bw würd ich speedbw bringen,da es schon server mit bedwars gibt,allerdings gibt es kein server mit speedbedwars,sprich die maps liegen nicht so weit auseinander,man spawnt mit items sprich ; Schwert,volle rüstung,2 stacks Sandsteine (oder mehr),2 webs,Knockbackstick,bisschen essen und das Ziel ist es ganz normal das gegnerische Bett zu holen.Anfangs kann man starten mit 2x1 und 2x2 allerdings kann man dann später 2x4 oder 4x4 hinzufügen.bei fragen discord melden..

**Comment by xxAROX** [comment]
ne

**Comment by xxFLORII** [comment]
Planned comeback for SpeedBW in circa 2 weeks
